---
sudo: false
language: c
compiler:
    - gcc
    - clang
script: make
addons:
    apt:
        packages:
        - build-essential
        - libevent-2.0-5
        - libevent-dev
        - libcairo2
        - libcairo2-dev
        - libpango1.0-0
        - libpango1.0-dev
